site_name: Dr. Khan's Computer Science Courses @ San Diego Miramar College

theme:
  name: material

extra:
  analytics:
    provider: google
    property: G-5SGJZZD5EZ

extra_css:
  - stylesheets/extra.css
  - stylesheets/course.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/semester.js
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/faq.js

nav:
  - Dashboard: index.md

  - CISC 179<br>Python Programming:
      - Syllabus: python/syllabus.md

  - CISC 187<br>Data Structures in C++:
      - Dashboard: data-structures/index.md
      - Syllabus: data-structures/syllabus.md
      - Lectures & Labs: data-structures/16_weeks_semester.md
      - Resources: data-structures/resources/index.md

  - CISC 191<br>Intermediate Java:
      - Syllabus: java/syllabus.md

  - CISC 192<br>C/C++ Programming:
      - Syllabus: cpp/syllabus.md

  - CISC 211<br>Assembly Language:
      - Dashboard: assembly/index.md
      - Syllabus: assembly/syllabus.md
      - Lectures & Labs: assembly/8_weeks_semester.md
      - Resources: assembly/resources/index.md